let questions = [
    'be a genius and know everything or be amazing at any activity you trie',
    'dine alone or watch a good movie by yoursel',
    'end world hunger or stop crime all over the United State',
    'wear pants 3 sizes too big or shoes 3 sizes too smal',
    'go into the past and meet your ancestors or go into the future and meet your great-great-grandchildre',
    'always drink bad coffee or always eat stale brea',
    'invent something for the first time or discover something for the first time',
    'be a multi-millionaire in 1900 or a middle-class person today',
    'be the God of light or the God of darkness',
    'never have to wait at lights or never have to wait for your food',
    'live in an RV or live on a sailboat',
    'read the book or watch the movie version of the book',
    'look and feel 20 years younger from the neck down or the neck up',
    'be able to take a shower whenever you want but the water pressure is always really low or take the perfect shower but only be able to do it once a month',
    "date your best friend's sibling or have your best friend date your sibling",
    'be able to talk to wild animals or domesticated animals',
    'let a random stranger lick you or you lick a random stranger',
    'have five feet or five hands',
    'have a free day off on Friday or Monday',
    'be bored all the time or too busy all the time',
    "have a song that you hate stuck in your head or an itch you can't reach for a year",
    'achieve world peace or solve world hunger',
    'spend eight hours listening to someone scratch a chalkboard with their nails or have a mosquito buzzing around your head as you try to sleep each night for a month',
    'have perfect skin but bad teeth or a perfect smile but bad skin',
    'burn your tongue or burn the top of your mouth',
    'have every minute feel like an hour or every hour feel like a minute',
    "always have a little rock in your shoe you can't find or always have a hangnail that gets caught on things",
    'lose all your money or lose your best friend',
    'make a million dollars or make a rocket',
    'spend time with your family or spend time with friends',
    'be a villain or a hero',
    'hate your dream job or have a dream job and never get paid',
    'never see your friend as a human or never see them at all',
    'live in the past or live in the present',
    "live where it's always dark or always light",
    'go to the aquarium or go to the zoo',
    'go to the moon or go to Mars',
    'eat candy for the rest of your life or eat cheeseburgers for the rest of your life',
    'eat ice cream or pizza in the morning',
    'live the same day for the rest of your life or live for only one day',
    'be able to talk to animals or be able to speak any language',
    'be able to talk your way out of trouble or fight your way out of trouble',
    'never be able to shower again or never be able to clip your toenails again',
    'be the last person in the world or be the best athlete in the world',
    'live in a world without problems or a world without poverty',
    'let your crush know you love them or hide your love for the rest of your life',
    'live in this same year for the rest of your life or live for one year in the future',
    'have free internet or have free coffee',
    'have free food or have free alcohol',
    'have too many warts or too many ulcers',
    'never be able to smell or never be able to fart',
    'never be able to see or never be able to hear',
    'go to an amusement park or go to the woods',
    'eat every meal with ketchup or vinegar',
    'be made publicly foolish or made publicly untrustworthy',
    'be able to speak French or Spanish',
    'eat meat for the rest of your life or eat vegetables',
    'spend 10 years in prison or 20 years on a deserted island',
    'have the ability to speak with dolphins or whales',
    'be the funniest person your friends know or the most trustworthy',
    'be a famous comedian or a famous writer',
    'lose the ability to speak or lose the ability to use your hands',
    'only be able to walk or only be able to jump',
    'date someone blind or date someone deaf',
    'lose your ability to read or lose your ability to eat',
    'have the ability to read minds or the ability to do sign language',
    'spend 10 years on an island or in the woods',
    'only be able to eat fish for the rest of your life or only be able to eat steak for the rest of your life',
    'be able to fly or be able to hunt',
    'your only mode of transportation be a bumpy car ride or a loud train ride',
    'have just enough money to get by or have to do something you hate and be rich',
    "be able to see your own future or everyone else's",
    'live your entire life in a big city or little city',
    'have more time or more money',
    'be the smartest person in the room or best looking',
    'be unable to control body hair or body odor',
    'be great at playing a musical instrument or great with money',
    'lose all the pictures you ever took or lose your memory',
    'live your whole life unable to eat or unable to drink',
    'live a long life but boring or a short life but interesting',
    'lose all your clothes in a fire or your computer',
    'play video games or watch movies',
    'eat the same dinner the rest of your life or eat rotten eggs',
    'be incredibly rich and boring or poor and interesting',
    "have a terrible job that paid well or a great job that didn't",
    'own a private island (your own island) or own a private jet',
    'drink sour milk or drink cat urine',
    'know your great great grandchildren but have no stories to tell or rely on your children to share the good stories forward',
    'get rich or get your dream home',
    'get mud on your shoes or get dog feces on your shoes',
    'take out the trash or take out the dog',
    'love someone or love your dog',
    'get one wish from a genie or one gift',
    'skip school or skip church',
    'let people punch you or let people kick you',
    'change your height whenever you want or change your hair whenever you want',
    'time travel or fly',
    'time travel or teleport',
    'live 100 years in the past or 100 years in the future',
    'be able to jump high or run fast',
    'be able to talk fast or take tests quickly',
    'have difficulty being able to think or speak',
    'not be able to have kids or not be able to see',
    'fart in public or pee your pants in public',
    'not have pubic hair or have hair all over your face',
    'live for one day with a boner or one day without an arm',
    'use a conifer cone to wipe your butt or use newspaper to wipe your butt',
    'make a cake out of mud or make a cake out of hair',
    'smell like a camel or smell like a skunk',
    'kiss a frog or kiss a llama',
    'lose a leg or lose an arm',
    'have no job or have no money',
    'fly to work or teleport to work',
    'be good at a sport or be good at making money',
    'fart on someone or be farted on',
    'have bad breath or have bad body odor',
    'get an STD or get a virus',
    'live life alone or live life supporting multiple people',
    'have a new car or have a new bike',
    'have 100 animals or 100 plants',
    'search for aliens or search for treasure',
    'have a bad day or have a broken nose',
    'be a celebrity for a day or be an animal for a day',
    'be the best friend or be the only friend',
    'see ghosts or see dead people',
    'know everything or not know anything',
    'work for the rest of your life or work for free for one year',
    'have one dollar or one lottery ticket',
    'speak every language or play every instrument',
    'master every song or master every craft',
    'love once or not love at all',
    'fall in love with an animal or fall in love with someone bad',
    'eat rotten apples or rotten fries',
    "make someone's day or make someone's hour",
    'have it be easy to learn or have it be easy to read',
    'look like a donkey or look like a monkey',
    'end your life happy or end your life rich',
    'use a napkin or use a towel',
    'take a bat to the face or take a golf club to the knee',
    'live without money or live without work',
    'work in a factory or work in a coal mine',
    'have one dance move or one pick-up line',
    'like life or live life',
    'have a rewind button in life or have a pause button in life',
    'wear a tin hat or a clown nose for the rest of your life',
    'have a great body for the rest of your life or a low IQ',
    'spend years of your life in a wheelchair or on life support',
    'have one chance or one opportunity',
    'be a handicap in life or be poor in life',
    'let your best friend win $10,000 or be able to fly for 10-minutes',
    'spend a year in prison or a decade in a cave',
    'change the world or change your life',
    'be the greatest in the world or be the greatest for your family',
    'be known around the world or known around your community',
    'feel rats or feel snakes',
    'feel sad or feel depressed',
    'meet your dead grandparents or meet a celebrity',
    'meet your future kids or meet your future self',
    'give everyone you meet high feels or give them wedgies',
    "know when you're going to d*e or how you're going to d*e",
    'd*e on an island or d*e in the forest',
    'go to the circus or go to the carnival',
    'go to Italy or go to France',
    'go to the dentist or go to the doctor',
    'find a way to cure cancer or find a way to give families to every orphan',
    "meet the person you'll marry or meet the person who will change your life",
    "be the person you'd like to be or let another person get better",
    'live without food or live without money',
    'eat a dozen rats or eat a dozen bugs',
    'live years alone or live years in safety',
    'set the world on fire or have the world drown in the ocean',
    'get stung by a bee or get bit by a snake',
    'see life in the future or see life in the past',
    'know what life means or decide what life means',
    'stop time or speed up time',
    'find a way to travel to space or find a way to help animals',
    'be ten years older or ten years younger',
    'be ten years old or eighty years old',
    'talk like a bird or bark like a dog for the rest of your life',
    'spend time with your parents or spend time with your kids',
    'jump or kneel every time someone spoke',
    'eat a spider or eat a bee',
    'want to know how your kids will look or how your grand kids will look',
    "know how much money you'll have in ten years or be happy for one day",
    'live free or live in poverty',
    'enter rooms announcing your name or always having to do jumping jacks',
    'get away with lying or always know when someone is lying',
    'be ten minutes late or always be thirty minutes early',
    'always be itchy or always be sneezing',
    'have all rights reserved as an artist or have your work trademarked',
    'be able to walk on water or walk across the sand',
    'cheat on someone or be cheated on',
    'eat animals or eat vegetables',
    'end a movie or end a book',
    'have a job in science or have a job in government',
    'fly or cure cancer for the world',
    'be famous or protect your family',
    'marry someone famous or be someone famous',
    'be able to wake up on command or go to sleep on command',
    'be a great partner or be a great friend',
    "be able to read someone's mind or read really quickly",
    'give to charity or have a job in charity',
    'have your dream girl or your dream car',
    'be an athlete or someone famous',
    'be Instagram famous or movie star famous',
    'read books for the rest of your life or watch movies',
    'lose a close friend or lose a close family member',
    'have two dogs or two cats',
    'never marry or never have kids',
    'live a year in Paris or a year in Italy',
    'be the person to survive cancer or the person to be famous',
    'have a sports car or be rich',
    'have a job that paid well or work for a great boss',
    'have tons of free time or have no friends',
    'eat a rat or eat a mouse',
    'be able to run really fast or jump really high',
    'go surfing or go snowboarding',
    'go to the mountains or go to the beach',
    'a girl text you or call you on the phone',
    'work in a nail salon or work in a hair salon',
    'work for your dad or work for your mom',
    'spend a year with your sister or a year with your mom',
    'be good to others or have others be good to you',
    'have an easy time meeting friends or an easy time meeting boyfriends',
    'lose a sports match or lose a boyfriend',
    'd#e alone or d#e with your spouse',
    'eat food with a straw or eat food with a knife',
    'have your friend disown you or have your family know all your secrets',
    'eat alone for the rest of your life or always be hungry',
    'never meet your parents or spend years in prison',
    'never be able to clip your toenails or never be able to put on deodorant',
    'always burp when you see someone or always fart',
    'go out to dinner or go to a concert',
    'spend time together or go to an event',
    'always say everything on your mind or never speak again',
    "believe everything you're told or have the ability to lie",
    'have everything you do live-streamed or have a television show',
    'be stripped of everything you own or fall terminally ill with cancer',
    'go on vacation to Mexico or go to Iceland',
    'go on a bike ride or go for a walk',
    'date a guy every day for life or date an elephant for life',
]

function createQuestion() {
    let question = questions[Math.round(Math.random() * questions.length)];

    let returner = question?.split(' or ');
    return returner;
};

module.exports = { createQuestion };